name: musheet_client
description: MuSheet Serverpod client library for Flutter
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  serverpod_client: 3.1.1

dev_dependencies:
  lints: ^3.0.0